import discord
import config #imports the config.py file, which contains the bot's token. This allows the bot to access the token without hardcoding it into the code, keeping it hidden from anyone who looks at the code.

#invite link: https://discord.com/oauth2/authorize?client_id=1550582722555019435&permissions=120832&integration_type=0&scope=bot

class Client(discord.Client): #pulls discord client
    async def on_ready(self): #onready is a predefined function that runs when the bot is ready, it iwll run the code inside it when the bot is ready
        print(f'Logged in as {self.user}')
        #self.user is the bot's user object, which contains information about the bot, such as its username and ID. The f-string is used to format the string with the bot's username and ID.
    async def on_message(self, message): #onmessage is a predefined function that runs when a message is sent in a channel the bot has access to. It will run the code inside it when a message is sent.
        print(f'Message from {message.author}: {message.content}')

intents = discord.Intents.default() #creates an instance of the Intents class, which is used to specify which events the bot should listen to. The default() method returns an instance of the Intents class with all events enabled.
intents.message_content = True #enables the messages event, which is triggered when a message is sent in a channel.
intents.typing = True #enables the typing event, which is triggered when a user starts typing in a channel.

client = Client(intents=intents) #creates an instance of the Client class, passing in the intents object as an argument. This allows the bot to listen to the events specified in the intents object.
client.run(config.TOKEN) #imports the TOKEN variable from the config.py file and passes it to the run() method, which starts the bot and connects it to Discord using the provided token.

# the bot will read the last X strings, but we'll use 1000 in place of X strings from a channel starting from when the bot is added, the strings are chosen based on the whitespace between them, so a sentence like:
# "i ate some taco's tuesday\_night! i got $2 off [https://youtube.com](https://youtube.com) 😌 👀👀👀 @gzapple <@78123871628312132> етвкет ድትይምትድጅት <{L}?}፡{}<?"}፡"<}+$% " it will read: 'i' 'ate' 'taco's' 'tuesday\_night' 'i' 'got' '$2' 'off' '[https://youtube.com](https://youtube.com)' '😌' '👀👀👀' '@gzapple' '<@78123871628312132>' 'етвкет' 'ድትይምትድጅት' '<{L}?}፡{}<?"}፡"<}+$%'
# from these 1000 strings it will assign an array value per string
# there is a random seed , this random seed will pick out at random any of these strings from the 1k array. there will be another random seed for how many strings it will pick out from these 1000
# these random seeds can either be generated by time, like how C you can generate random values based on real time from millisceonds it will then have another random seed to make the order of strings random, so that the eventual output is a combination of random strings and characters at a random size randomly picked. i am not sure what the word character limit for bott outputs are, but thats the only limitation besides picking out the last strings
# the bot will send a random message based on what was stated previously. so lests say within a conversation the bot just garbles out stuff 
# the bot can automatically respond to you if: it gets pinged, if it gets replied with mentioned turned on, if a role that was assigned to it gets pinged, if any bot pings it (either as @BOTNAME or as <@insert\_bot\_id\_from\_discord> )(lets say another genai bot pings the bot, it should respond to it )
# BOT SETTING STUFF:
# you can set how much randomization you want (a limit to how many strings itll read based on X strings from a channel), extend message read history (reading before bot was added + extend the read to 5000 strings)
# you can adjust the message interval the bot will send, between 1-20 messages. what does this mean? excluding the bot's own messages, every X messages the bot will send
# any links, depending if they were embeded or not can get sent
# options to allow the bot to read server wide or to specific channels options to allow link embeds
# PY FILE DELEGATION:
# bot.py - responsible for the bot's main functionality, such as connecting to Discord, reading messages, and sending messages.
# memory.py  - responsible of storing and retrieving the bot's memory, such as the last X strings read from a channel.
# genai.py - responsible for generating random messages based on the bot's memory and the randomization settings.
# triggers.py - responsible for handling triggers, such as when the bot is pinged or mentioned, and responding accordingly.
# settings.py - responsible for handling the bot's settings, such as the randomization settings and message interval.